<a href="https://colab.research.google.com/github/tanujk21/tanujk21-ML-Learning/blob/main/Feature_scalilng_03_ordinal%26label_encoder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
from google.colab import files
uploaded=files.upload()

Saving customer.csv to customer.csv

In [5]:
df=pd.read_csv("customer.csv")
df.sample(5)

    age  gender review education purchased
48   39  Female   Good        UG       Yes
26   53  Female   Poor        PG        No
22   18  Female   Poor        PG       Yes
14   15    Male   Poor        PG       Yes
3    72  Female   Good        PG        No

In [6]:
#here can see that all are mostly categorical column
#In this we will do encoding ordinal->review and education and on pirchased->label
df=df.iloc[:,2:]
df

     review education purchased
0   Average    School        No
1      Poor        UG        No
2      Good        PG        No
3      Good        PG        No
4   Average        UG        No
5   Average    School       Yes
6      Good    School        No
7      Poor    School       Yes
8   Average        UG        No
9      Good        UG       Yes
10     Good        UG       Yes
11     Good        UG       Yes
12     Poor    School        No
13  Average    School        No
14     Poor        PG       Yes
15     Poor        UG        No
16     Poor        UG       Yes
17     Poor        UG       Yes
18     Good    School        No
19     Poor        PG       Yes
20  Average    School       Yes
21  Average        PG        No
22     Poor        PG       Yes
23     Good    School        No
24  Average        PG       Yes
25     Good    School        No
26     Poor        PG        No
27     Poor        PG        No
28     Poor    School        No
29  Average        UG       Yes
30  Average        UG        No
31     Poor    School       Yes
32  Average        UG       Yes
33     Good        PG       Yes
34  Average    School        No
35     Poor    School       Yes
36     Good        UG       Yes
37  Average        PG       Yes
38     Good    School        No
39     Poor        PG        No
40     Good    School        No
41     Good        PG       Yes
42     Good        PG       Yes
43     Poor        PG        No
44  Average        UG        No
45     Poor        PG       Yes
46     Poor        PG        No
47     Good        PG       Yes
48     Good        UG       Yes
49     Good        UG        No

In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [17]:
x_train

     review education
45     Poor        PG
2      Good        PG
20  Average    School
38     Good    School
13  Average    School
37  Average        PG
9      Good        UG
26     Poor        PG
24  Average        PG
5   Average    School
6      Good    School
15     Poor        UG
8   Average        UG
48     Good        UG
36     Good        UG
21  Average        PG
49     Good        UG
47     Good        PG
4   Average        UG
41     Good        PG
33     Good        PG
7      Poor    School
44  Average        UG
28     Poor    School
14     Poor        PG
10     Good        UG
29  Average        UG
25     Good    School
22     Poor        PG
46     Poor        PG
40     Good    School
12     Poor    School
32  Average        UG
30  Average        UG
31     Poor    School
23     Good    School
27     Poor        PG
43     Poor        PG
17     Poor        UG
18     Good    School

In [18]:
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [19]:
oe.fit(x_train)  #fit on train and transform on both

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [20]:
x_train=oe.transform(x_train)
x_test=oe.transform(x_test)

In [21]:
x_train

array([[0., 2.],
       [2., 2.],
       [1., 0.],
       [2., 0.],
       [1., 0.],
       [1., 2.],
       [2., 1.],
       [0., 2.],
       [1., 2.],
       [1., 0.],
       [2., 0.],
       [0., 1.],
       [1., 1.],
       [2., 1.],
       [2., 1.],
       [1., 2.],
       [2., 1.],
       [2., 2.],
       [1., 1.],
       [2., 2.],
       [2., 2.],
       [0., 0.],
       [1., 1.],
       [0., 0.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [2., 0.],
       [0., 2.],
       [0., 2.],
       [2., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [2., 0.],
       [0., 2.],
       [0., 2.],
       [0., 1.],
       [2., 0.]])

In [22]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [23]:
le.fit(y_train)

LabelEncoder()

In [25]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [26]:
y_train=le.transform(y_train)
y_test=le.transform(y_test)

In [27]:
y_train

array([1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0])